

hex = data.frame(country = "", x = 0, y = 0, stringsAsFactors = FALSE)


hex[1,] = c("France", 0, 0)
hex = rbind(hex, c("France", 1, 1))
hex = rbind(hex,c("France", 2, 0))
hex = rbind(hex,c("France", -1, 1))
hex = rbind(hex,c("France", -2, 0))
hex = rbind(hex,c("France", -1, -1))
hex = rbind(hex,c("France", 1, -1))
hex = rbind(hex,c("Monaco", 2, -2))
hex = rbind(hex,c("Andorra", 0, -2))
hex = rbind(hex,c("Spain", -2, -2))
hex = rbind(hex,c("Spain", -3, -1))
hex = rbind(hex,c("Spain", -3, -3))
hex = rbind(hex,c("Spain", -4, -2))
hex = rbind(hex,c("Spain", -5, -1))
hex = rbind(hex,c("Portugal", -6, -2))
hex = rbind(hex,c("Portugal", -5, -3))
hex = rbind(hex,c("Azores", -13, -3))
hex = rbind(hex,c("Madeira", -11, -5))
hex = rbind(hex,c("Gibraltar", -4, -4))
hex = rbind(hex,c("Guernsey and Jersey", -3, 1))
hex = rbind(hex,c("Belgium", 0, 2))
hex = rbind(hex,c("Belgium", 2, 2))
hex = rbind(hex,c("Luxembourg", 3, 1))
hex = rbind(hex,c("Netherlands", 1, 3))
hex = rbind(hex,c("Netherlands", 3, 3))
hex = rbind(hex,c("United Kingdom", -3, 3))
hex = rbind(hex,c("United Kingdom", -2, 4))
hex = rbind(hex,c("United Kingdom", -3, 5))
hex = rbind(hex,c("United Kingdom", -5, 3))
hex = rbind(hex,c("United Kingdom", -2, 6))
hex = rbind(hex,c("United Kingdom", -3, 7))
hex = rbind(hex,c("United Kingdom", -4, 4))
hex = rbind(hex,c("Isle of Man", -5, 5))
hex = rbind(hex,c("Ireland", -8, 6))
hex = rbind(hex,c("Iceland", -16, 10))
hex = rbind(hex,c("Faroe Islands", -12, 8))

hex = rbind(hex,c("Germany", 4, 4))
hex = rbind(hex,c("Germany", 5, 3))
hex = rbind(hex,c("Germany", 4, 2))
hex = rbind(hex,c("Germany", 5, 1))
hex = rbind(hex,c("Germany", 5, 5))
hex = rbind(hex,c("Germany", 6, 4))
hex = rbind(hex,c("Germany", 7, 3))
hex = rbind(hex,c("Germany", 6, 2))
hex = rbind(hex,c("Germany", 7, 1))
hex = rbind(hex,c("Switzerland", 4, 0))
hex = rbind(hex,c("Liechtenstein", 6, 0))
hex = rbind(hex,c("Austria", 8, 0))
hex = rbind(hex,c("Italy", 3, -1))
hex = rbind(hex,c("Italy", 5, -1))
hex = rbind(hex,c("Italy", 7, -1))
hex = rbind(hex,c("Italy", 4, -2))
hex = rbind(hex,c("Italy", 5, -3))
hex = rbind(hex,c("Italy", 6, -4))
hex = rbind(hex,c("Vatican City", 7, -3))
hex = rbind(hex,c("San Marino", 6, -2))
hex = rbind(hex,c("Malta", 8, -6))
hex = rbind(hex,c("Czech Republic", 8, 2))
hex = rbind(hex,c("Czech Republic", 9, 1))
hex = rbind(hex,c("Poland", 9, 3))
hex = rbind(hex,c("Poland", 8, 4))
hex = rbind(hex,c("Poland", 10, 4))
hex = rbind(hex,c("Poland", 11, 3))
hex = rbind(hex,c("Slovakia", 10, 2))
hex = rbind(hex,c("Slovenia", 10, 0))
hex = rbind(hex,c("Denmark", 6, 6))
hex = rbind(hex,c("Sweden", 8, 8))
hex = rbind(hex,c("Sweden", 8, 8))
hex = rbind(hex,c("Norway", 6, 8))
hex = rbind(hex,c("Finland", 10, 8))
hex = rbind(hex,c("Estonia", 11, 7))
hex = rbind(hex,c("Latvia", 12, 6))
hex = rbind(hex,c("Lithuania", 11, 5))
hex = rbind(hex,c("Belarus", 12, 4))
hex = rbind(hex,c("Hungary", 11, 1))
hex = rbind(hex,c("Ukraine", 13, 3))
hex = rbind(hex,c("Ukraine", 12, 2))
hex = rbind(hex,c("Ukraine", 14, 2))
hex = rbind(hex,c("Ukraine", 13, 1))
hex = rbind(hex,c("Ukraine", 15, 1))
hex = rbind(hex,c("Republic of Moldova", 14, 0))
hex = rbind(hex,c("Romania", 13, -1))
hex = rbind(hex,c("Romania", 15, -1))
hex = rbind(hex,c("Serbia", 12, 0))
hex = rbind(hex,c("Croatia", 11, -1))
hex = rbind(hex,c("Bosnia and Herzegovina", 12, -2))
hex = rbind(hex,c("Montenegro", 13, -3))
hex = rbind(hex,c("Albania", 12, -4))
hex = rbind(hex,c("Bulgaria", 14, -2))
hex = rbind(hex,c("Republic of Macedonia", 15, -3))
hex = rbind(hex,c("Greece", 13, -5))
hex = rbind(hex,c("Greece", 14, -4))
hex = rbind(hex,c("Cyprus", 16, -6))
hex = rbind(hex,c("Turkey", 16, -2))
hex = rbind(hex,c("Turkey", 17, -3))
hex = rbind(hex,c("Turkey", 18, -4))
hex = rbind(hex,c("Turkey", 19, -5))
hex = rbind(hex,c("Turkey", 20, -4))
hex = rbind(hex,c("Turkey", 21, -5))
hex = rbind(hex,c("Turkey", 22, -4))
hex = rbind(hex,c("Turkey", 23, -5))

hex = rbind(hex,c("Armenia", 24, -4))
hex = rbind(hex,c("Georgia", 23, -3))
hex = rbind(hex,c("Azerbaijan", 25, -3))

hex = rbind(hex,c("Russian Federation", 13, 5))
hex = rbind(hex,c("Russian Federation", 14, 4))
hex = rbind(hex,c("Russian Federation", 15, 3))
hex = rbind(hex,c("Russian Federation", 16, 2))
hex = rbind(hex,c("Russian Federation", 17, 1))
hex = rbind(hex,c("Russian Federation", 18, 0))
hex = rbind(hex,c("Russian Federation", 20, 0))
hex = rbind(hex,c("Russian Federation", 22, 0))
hex = rbind(hex,c("Russian Federation", 23, -1))
hex = rbind(hex,c("Russian Federation", 25, -1))
hex = rbind(hex,c("Russian Federation", 24, -2))

hex = rbind(hex,c("Russian Federation", 26, -2))
hex = rbind(hex,c("Russian Federation", 27, -1))
hex = rbind(hex,c("Russian Federation", 29, -1))
hex = rbind(hex,c("Russian Federation", 31, -1))
###########################################################################
###########################################################################
## Africa
###########################################################################
###########################################################################
hex = rbind(hex,c("Morocco", -4, -6))
hex = rbind(hex,c("Morocco", -5, -7))
hex = rbind(hex,c("Morocco", -3, -7))
hex = rbind(hex,c("Morocco", -6, -8))
hex = rbind(hex,c("Mali", -3, -9))
hex = rbind(hex,c("Mali", -5, -9))
hex = rbind(hex,c("Western Sahara", -7, -9))
hex = rbind(hex,c("Canary Islands", -9, -7))

hex = rbind(hex,c("Mauritania", -6, -10))

hex = rbind(hex,c("Senegal", -8, -10))
hex = rbind(hex,c("Senegal", -7, -11))
hex = rbind(hex,c("Cape Verde", -12, -10))

hex = rbind(hex,c("Gambia", -9, -11))

hex = rbind(hex,c("Guinea", -4, -10))
hex = rbind(hex,c("Guinea", -2, -10))
hex = rbind(hex,c("Guinea-Bissau", -5, -11))
hex = rbind(hex,c("Guinea-Bissau", -3, -11))
hex = rbind(hex,c("Sierra Leone", -8, -12))
hex = rbind(hex,c("Liberia", -7, -13))

hex = rbind(hex,c("Cote d'Ivoire", -5, -13))
hex = rbind(hex,c("Cote d'Ivoire", -6, -14))
hex = rbind(hex,c("Cote d'Ivoire", -6, -12))

hex = rbind(hex,c("Ghana", -3, -13))
hex = rbind(hex,c("Ghana", -4, -14))
hex = rbind(hex,c("Ghana", -4, -12))
hex = rbind(hex,c("Togo", -3, -15))
hex = rbind(hex,c("Benin", -2, -14))

hex = rbind(hex,c("Burkina Faso", 0, -10))
hex = rbind(hex,c("Burkina Faso", -1, -11))

hex = rbind(hex,c("Algeria", -1, -7))
hex = rbind(hex,c("Algeria", -2, -8))
hex = rbind(hex,c("Algeria", -4, -8))
hex = rbind(hex,c("Algeria", 0, -8))
hex = rbind(hex,c("Algeria", -1, -9))

hex = rbind(hex,c("Niger", 1, -9))
hex = rbind(hex,c("Niger", 3, -9))
hex = rbind(hex,c("Niger", 2, -10))

hex = rbind(hex,c("Nigeria", 1, -11))
hex = rbind(hex,c("Nigeria", 0, -12))
hex = rbind(hex,c("Nigeria", -2, -12))
hex = rbind(hex,c("Nigeria", 2, -12))
hex = rbind(hex,c("Nigeria", -1, -13))
hex = rbind(hex,c("Nigeria", 1, -13))
hex = rbind(hex,c("Nigeria", 3, -11))
hex = rbind(hex,c("Nigeria", 5, -11))
hex = rbind(hex,c("Nigeria", 4, -10))
hex = rbind(hex,c("Nigeria", 7, -11))
hex = rbind(hex,c("Nigeria", 6, -12))
hex = rbind(hex,c("Nigeria", 4, -12))
hex = rbind(hex,c("Nigeria", 3, -13))
hex = rbind(hex,c("Nigeria", 5, -13))
hex = rbind(hex,c("Nigeria", 0, -14))
hex = rbind(hex,c("Nigeria", 2, -14))
hex = rbind(hex,c("Nigeria", -1, -15))
hex = rbind(hex,c("Nigeria", 1, -15))
hex = rbind(hex,c("Nigeria", 7, -13))


hex = rbind(hex,c("Chad", 5, -9))
hex = rbind(hex,c("Chad", 6, -10))

hex = rbind(hex,c("Tunisia", 2, -8))
hex = rbind(hex,c("Tunisia", 4, -8))

hex = rbind(hex,c("Libya", 6, -8))




hex = rbind(hex,c("Egypt", 7, -9))
hex = rbind(hex,c("Egypt", 9, -9))
hex = rbind(hex,c("Egypt", 11, -9))
hex = rbind(hex,c("Egypt", 13, -9))
hex = rbind(hex,c("Egypt", 10, -10))
hex = rbind(hex,c("Egypt", 12, -10))
hex = rbind(hex,c("Egypt", 8, -10))
hex = rbind(hex,c("Egypt", 9, -11))
hex = rbind(hex,c("Egypt", 8, -8))
hex = rbind(hex,c("Egypt", 11, -11))

hex = rbind(hex,c("Sudan", 10, -12))
hex = rbind(hex,c("Sudan", 12, -12))
hex = rbind(hex,c("Sudan", 8, -12))
hex = rbind(hex,c("Sudan", 9, -13))
hex = rbind(hex,c("Sudan", 11, -13))
hex = rbind(hex,c("Eritrea", 13, -13))
hex = rbind(hex,c("Djibouti", 14, -14))
hex = rbind(hex,c("Chad", 11, -11))
hex = rbind(hex,c("Chad", 11, -11))


hex = rbind(hex,c("Cameroon", 2, -16))
hex = rbind(hex,c("Cameroon", 3, -15))
hex = rbind(hex,c("Cameroon", 4, -14))

hex = rbind(hex,c("Equatorial Guinea", 1, -17))
hex = rbind(hex,c("Sao Tome and Principe", -2, -18))

hex = rbind(hex,c("Gabon", 2, -18))
hex = rbind(hex,c("Congo", 3, -19))

hex = rbind(hex,c("Angola", 4, -20))
hex = rbind(hex,c("Angola", 2, -20))
hex = rbind(hex,c("Angola", 3, -21))

hex = rbind(hex,c("Saint Helena, Ascension and Tristan da Cunha", -7, -21))

hex = rbind(hex,c("Zambia", 5, -21))
hex = rbind(hex,c("Zambia", 7, -21))
hex = rbind(hex,c("Malawi", 9, -21))
hex = rbind(hex,c("Malawi", 10, -22))

hex = rbind(hex,c("Mozambique", 12, -22))
hex = rbind(hex,c("Mozambique", 11, -23))
hex = rbind(hex,c("Mozambique", 13, -23))

hex = rbind(hex,c("Seychelles", 22, -18))
hex = rbind(hex,c("Comoros", 17, -21))
hex = rbind(hex,c("Mayotte", 18, -22))
hex = rbind(hex,c("Madagascar", 18, -24))
hex = rbind(hex,c("Madagascar", 19, -23))
hex = rbind(hex,c("Madagascar", 20, -22))
hex = rbind(hex,c("Reunion", 24, -23))
hex = rbind(hex,c("Mauritius", 25, -22))

hex = rbind(hex,c("Namibia", 4, -22))
hex = rbind(hex,c("Botswana", 6, -22))

hex = rbind(hex,c("Zimbabwe", 8, -22))
hex = rbind(hex,c("Zimbabwe", 9, -23))
hex = rbind(hex,c("Swaziland", 12, -24))
hex = rbind(hex,c("Lesotho", 10, -24))

hex = rbind(hex,c("South Africa", 8, -24))
hex = rbind(hex,c("South Africa", 7, -23))
hex = rbind(hex,c("South Africa", 5, -23))
hex = rbind(hex,c("South Africa", 6, -24))
hex = rbind(hex,c("South Africa", 7, -25))
hex = rbind(hex,c("South Africa", 9, -25))

hex = rbind(hex,c("Democratic Republic of the Congo", 5, -15))
hex = rbind(hex,c("Democratic Republic of the Congo", 4, -16))
hex = rbind(hex,c("Democratic Republic of the Congo", 6, -16))
hex = rbind(hex,c("Democratic Republic of the Congo", 5, -17))
hex = rbind(hex,c("Democratic Republic of the Congo", 3, -17))
hex = rbind(hex,c("Democratic Republic of the Congo", 4, -18))
hex = rbind(hex,c("Democratic Republic of the Congo", 5, -19))
hex = rbind(hex,c("Democratic Republic of the Congo", 6, -20))

hex = rbind(hex,c("Central African Republic", 6, -14))

hex = rbind(hex,c("South Sudan", 8, -14))
hex = rbind(hex,c("South Sudan", 10, -14))

hex = rbind(hex,c("Ethiopia", 12, -14))
hex = rbind(hex,c("Ethiopia", 13, -15))
hex = rbind(hex,c("Ethiopia", 11, -15))
hex = rbind(hex,c("Ethiopia", 9, -15))
hex = rbind(hex,c("Ethiopia", 7, -15))
hex = rbind(hex,c("Ethiopia", 12, -16))
hex = rbind(hex,c("Ethiopia", 10, -16))
hex = rbind(hex,c("Ethiopia", 8, -16))
hex = rbind(hex,c("Ethiopia", 9, -17))
hex = rbind(hex,c("Ethiopia", 11, -17))
hex = rbind(hex,c("Ethiopia", 14, -16))

hex = rbind(hex,c("Somalia", 15, -15))
hex = rbind(hex,c("Somalia", 16, -16))

hex = rbind(hex,c("Kenya", 15, -17))
hex = rbind(hex,c("Kenya", 13, -17))
hex = rbind(hex,c("Kenya", 14, -18))
hex = rbind(hex,c("Kenya", 12, -18))
hex = rbind(hex,c("Kenya", 16, -18))

hex = rbind(hex,c("Uganda", 10, -18))
hex = rbind(hex,c("Uganda", 8, -18))
hex = rbind(hex,c("Uganda", 6, -18))
hex = rbind(hex,c("Uganda", 7, -17))
hex = rbind(hex,c("Uganda", 7, -19))

hex = rbind(hex,c("Rwanda", 9, -19))
hex = rbind(hex,c("Rwanda", 8, -20))

hex = rbind(hex,c("Burundi", 11, -19))
hex = rbind(hex,c("Burundi", 10, -20))

hex = rbind(hex,c("Tanzania", 13, -19))
hex = rbind(hex,c("Tanzania", 15, -19))
hex = rbind(hex,c("Tanzania", 12, -20))
hex = rbind(hex,c("Tanzania", 14, -20))
hex = rbind(hex,c("Tanzania", 11, -21))
hex = rbind(hex,c("Tanzania", 13, -21))

hex = rbind(hex,c("French Southern and Antarctic Lands", 31, -27))
hex = rbind(hex,c("Christmas Island", 61, -21))


###########################################################################
###########################################################################
## Middle East
###########################################################################
###########################################################################

hex = rbind(hex,c("Syrian Arab Republic", 20, -6))
hex = rbind(hex,c("Syrian Arab Republic", 21, -7))
hex = rbind(hex,c("Lebanon", 19, -7))

hex = rbind(hex,c("Jordan", 18, -8))
hex = rbind(hex,c("State of Palestine", 17, -9))
hex = rbind(hex,c("Israel", 15, -9))

hex = rbind(hex,c("Iraq", 22, -6))
hex = rbind(hex,c("Iraq", 24, -6))
hex = rbind(hex,c("Iraq", 23, -7))
hex = rbind(hex,c("Iraq", 25, -7))

hex = rbind(hex,c("Iran", 25, -5))
hex = rbind(hex,c("Iran", 27, -5))
hex = rbind(hex,c("Iran", 26, -6))
hex = rbind(hex,c("Iran", 28, -6))
hex = rbind(hex,c("Iran", 27, -7))
hex = rbind(hex,c("Iran", 29, -7))
hex = rbind(hex,c("Iran", 26, -8))
hex = rbind(hex,c("Iran", 28, -8))
hex = rbind(hex,c("Iran", 27, -9))

hex = rbind(hex,c("Turkmenistan", 28, -4))
hex = rbind(hex,c("Uzbekistan", 29, -5))
hex = rbind(hex,c("Uzbekistan", 30, -4))
hex = rbind(hex,c("Uzbekistan", 29, -3))
hex = rbind(hex,c("Uzbekistan", 31, -3))

hex = rbind(hex,c("Afghanistan", 30, -6))
hex = rbind(hex,c("Afghanistan", 32, -6))
hex = rbind(hex,c("Afghanistan", 31, -7))
hex = rbind(hex,c("Afghanistan", 30, -8))
hex = rbind(hex,c("Tajikistan", 31, -5))
hex = rbind(hex,c("Kyrgyzstan", 32, -4))
hex = rbind(hex,c("Kazakhstan", 28, -2))
hex = rbind(hex,c("Kazakhstan", 30, -2))

hex = rbind(hex,c("Saudi Arabia", 20, -8))
hex = rbind(hex,c("Saudi Arabia", 22, -8))
hex = rbind(hex,c("Saudi Arabia", 19, -9))
hex = rbind(hex,c("Saudi Arabia", 21, -9))

hex = rbind(hex,c("Yemen", 20, -10))
hex = rbind(hex,c("Yemen", 22, -10))
hex = rbind(hex,c("Yemen", 21, -11))
hex = rbind(hex,c("Yemen", 23, -11))

hex = rbind(hex,c("Kuwait", 24, -8))
hex = rbind(hex,c("Bahrain", 23, -9))
hex = rbind(hex,c("Qatar", 24, -10))
hex = rbind(hex,c("Oman", 24, -12))
hex = rbind(hex,c("United Arab Emirates", 25, -11))

###########################################################################
###########################################################################
## Asia
###########################################################################
###########################################################################
hex = rbind(hex,c("Pakistan", 29, -9))
hex = rbind(hex,c("Pakistan", 31, -9))
hex = rbind(hex,c("Pakistan", 33, -9))
hex = rbind(hex,c("Pakistan", 35, -9))
hex = rbind(hex,c("Pakistan", 32, -8))
hex = rbind(hex,c("Pakistan", 34, -8))
hex = rbind(hex,c("Pakistan", 36, -8))
hex = rbind(hex,c("Pakistan", 33, -7))
hex = rbind(hex,c("Pakistan", 35, -7))
hex = rbind(hex,c("Pakistan", 37, -7))
hex = rbind(hex,c("Pakistan", 34, -6))
hex = rbind(hex,c("Pakistan", 36, -6))
hex = rbind(hex,c("Pakistan", 38, -6))
hex = rbind(hex,c("Pakistan", 28, -10))
hex = rbind(hex,c("Pakistan", 30, -10))
hex = rbind(hex,c("Pakistan", 32, -10))
hex = rbind(hex,c("Pakistan", 34, -10))
hex = rbind(hex,c("Pakistan", 33, -5))
hex = rbind(hex,c("Pakistan", 35, -5))
hex = rbind(hex,c("Pakistan", 37, -5))


hex = rbind(hex,c("India", 38, -4))
hex = rbind(hex,c("India", 40, -4))
hex = rbind(hex,c("India", 50, -4))
hex = rbind(hex,c("India", 52, -4))
hex = rbind(hex,c("India", 54, -4))
hex = rbind(hex,c("India", 56, -4))
hex = rbind(hex,c("India", 58, -4))
hex = rbind(hex,c("India", 60, -4))
hex = rbind(hex,c("India", 62, -4))
hex = rbind(hex,c("India", 39, -5))

hex = rbind(hex,c("India", 41, -5))
hex = rbind(hex,c("India", 43, -5))
hex = rbind(hex,c("India", 45, -5))
hex = rbind(hex,c("India", 47, -5))
hex = rbind(hex,c("India", 49, -5))
hex = rbind(hex,c("India", 51, -5))
hex = rbind(hex,c("India", 53, -5))
hex = rbind(hex,c("India", 55, -5))
hex = rbind(hex,c("India", 57, -5))
hex = rbind(hex,c("India", 59, -5))

hex = rbind(hex,c("India", 61, -5))
hex = rbind(hex,c("India", 40, -6))
hex = rbind(hex,c("India", 42, -6))
hex = rbind(hex,c("India", 44, -6))
hex = rbind(hex,c("India", 46, -6))
hex = rbind(hex,c("India", 48, -6))
hex = rbind(hex,c("India", 50, -6))
hex = rbind(hex,c("India", 52, -6))
hex = rbind(hex,c("India", 54, -6))
hex = rbind(hex,c("India", 56, -6))

hex = rbind(hex,c("India", 58, -6))
hex = rbind(hex,c("India", 60, -6))
hex = rbind(hex,c("India", 39, -7))
hex = rbind(hex,c("India", 41, -7))
hex = rbind(hex,c("India", 43, -7))
hex = rbind(hex,c("India", 45, -7))
hex = rbind(hex,c("India", 47, -7))
hex = rbind(hex,c("India", 49, -7))
hex = rbind(hex,c("India", 57, -7))
hex = rbind(hex,c("India", 59, -7))

hex = rbind(hex,c("India", 61, -7))
hex = rbind(hex,c("India", 38, -8))
hex = rbind(hex,c("India", 40, -8))
hex = rbind(hex,c("India", 42, -8))
hex = rbind(hex,c("India", 44, -8))
hex = rbind(hex,c("India", 46, -8))
hex = rbind(hex,c("India", 48, -8))
hex = rbind(hex,c("India", 50, -8))
hex = rbind(hex,c("India", 60, -8))
hex = rbind(hex,c("India", 37, -9))

hex = rbind(hex,c("India", 39, -9))
hex = rbind(hex,c("India", 41, -9))
hex = rbind(hex,c("India", 43, -9))
hex = rbind(hex,c("India", 45, -9))
hex = rbind(hex,c("India", 47, -9))
hex = rbind(hex,c("India", 49, -9))
hex = rbind(hex,c("India", 51, -9))
hex = rbind(hex,c("India", 36, -10))
hex = rbind(hex,c("India", 38, -10))
hex = rbind(hex,c("India", 40, -10))

hex = rbind(hex,c("India", 42, -10))
hex = rbind(hex,c("India", 44, -10))
hex = rbind(hex,c("India", 46, -10))
hex = rbind(hex,c("India", 48, -10))
hex = rbind(hex,c("India", 50, -10))
hex = rbind(hex,c("India", 52, -10))
hex = rbind(hex,c("India", 31, -11))
hex = rbind(hex,c("India", 33, -11))
hex = rbind(hex,c("India", 35, -11))
hex = rbind(hex,c("India", 37, -11))

hex = rbind(hex,c("India", 39, -11))
hex = rbind(hex,c("India", 41, -11))
hex = rbind(hex,c("India", 43, -11))
hex = rbind(hex,c("India", 45, -11))
hex = rbind(hex,c("India", 47, -11))
hex = rbind(hex,c("India", 49, -11))
hex = rbind(hex,c("India", 32, -12))
hex = rbind(hex,c("India", 34, -12))
hex = rbind(hex,c("India", 36, -12))
hex = rbind(hex,c("India", 38, -12))

hex = rbind(hex,c("India", 40, -12))
hex = rbind(hex,c("India", 42, -12))
hex = rbind(hex,c("India", 44, -12))
hex = rbind(hex,c("India", 46, -12))
hex = rbind(hex,c("India", 48, -12))
hex = rbind(hex,c("India", 33, -13))
hex = rbind(hex,c("India", 35, -13))
hex = rbind(hex,c("India", 37, -13))
hex = rbind(hex,c("India", 39, -13))
hex = rbind(hex,c("India", 41, -13))

hex = rbind(hex,c("India", 43, -13))
hex = rbind(hex,c("India", 45, -13))
hex = rbind(hex,c("India", 47, -13))
hex = rbind(hex,c("India", 32, -14))
hex = rbind(hex,c("India", 34, -14))
hex = rbind(hex,c("India", 36, -14))
hex = rbind(hex,c("India", 38, -14))
hex = rbind(hex,c("India", 40, -14))
hex = rbind(hex,c("India", 42, -14))
hex = rbind(hex,c("India", 44, -14))

hex = rbind(hex,c("India", 46, -14))
hex = rbind(hex,c("India", 33, -15))
hex = rbind(hex,c("India", 35, -15))
hex = rbind(hex,c("India", 37, -15))
hex = rbind(hex,c("India", 39, -15))
hex = rbind(hex,c("India", 41, -15))
hex = rbind(hex,c("India", 43, -15))
hex = rbind(hex,c("India", 45, -15))
hex = rbind(hex,c("India", 34, -16))
hex = rbind(hex,c("India", 36, -16))

hex = rbind(hex,c("India", 38, -16))
hex = rbind(hex,c("India", 40, -16))
hex = rbind(hex,c("India", 42, -16))
hex = rbind(hex,c("India", 44, -16))
hex = rbind(hex,c("India", 35, -17))
hex = rbind(hex,c("India", 37, -17))
hex = rbind(hex,c("India", 39, -17))
hex = rbind(hex,c("India", 41, -17))
hex = rbind(hex,c("India", 43, -17))
hex = rbind(hex,c("India", 34, -18))

hex = rbind(hex,c("India", 36, -18))
hex = rbind(hex,c("India", 38, -18))
hex = rbind(hex,c("India", 40, -18))
hex = rbind(hex,c("India", 42, -18))
hex = rbind(hex,c("India", 35, -19))
hex = rbind(hex,c("India", 37, -19))
hex = rbind(hex,c("India", 39, -19))
hex = rbind(hex,c("India", 41, -19))
hex = rbind(hex,c("India", 36, -20))
hex = rbind(hex,c("India", 38, -20))

hex = rbind(hex,c("India", 40, -20))
hex = rbind(hex,c("India", 37, -21))
hex = rbind(hex,c("India", 39, -21))


hex = rbind(hex,c("Nepal", 46, -4))
hex = rbind(hex,c("Nepal", 44, -4))
hex = rbind(hex,c("Nepal", 42, -4))

hex = rbind(hex,c("Sri Lanka", 45, -21))
hex = rbind(hex,c("Sri Lanka", 44, -22))
hex = rbind(hex,c("Sri Lanka", 46, -22))

hex = rbind(hex,c("Maldives", 34, -24))

hex = rbind(hex,c("Bhutan", 48, -4))

hex = rbind(hex,c("Bangladesh", 50, -6))
hex = rbind(hex,c("Bangladesh", 52, -6))
hex = rbind(hex,c("Bangladesh", 54, -6))
hex = rbind(hex,c("Bangladesh", 51, -7))
hex = rbind(hex,c("Bangladesh", 53, -7))
hex = rbind(hex,c("Bangladesh", 55, -7))
hex = rbind(hex,c("Bangladesh", 52, -8))
hex = rbind(hex,c("Bangladesh", 54, -8))
hex = rbind(hex,c("Bangladesh", 56, -8))
hex = rbind(hex,c("Bangladesh", 58, -8))

hex = rbind(hex,c("Bangladesh", 53, -9))
hex = rbind(hex,c("Bangladesh", 55, -9))
hex = rbind(hex,c("Bangladesh", 57, -9))
hex = rbind(hex,c("Bangladesh", 59, -9))
hex = rbind(hex,c("Bangladesh", 54, -10))
hex = rbind(hex,c("Bangladesh", 56, -10))
hex = rbind(hex,c("Bangladesh", 58, -10))

hex = rbind(hex,c("Myanmar", 60, -10))
hex = rbind(hex,c("Myanmar", 61, -9))
hex = rbind(hex,c("Myanmar", 62, -8))
hex = rbind(hex,c("Myanmar", 62, -10))
hex = rbind(hex,c("Myanmar", 61, -11))
hex = rbind(hex,c("Myanmar", 62, -12))

hex = rbind(hex,c("Lao People's Democratic Republic", 63, -9))

hex = rbind(hex,c("Thailand", 64, -10))
hex = rbind(hex,c("Thailand", 63, -11))
hex = rbind(hex,c("Thailand", 64, -12))
hex = rbind(hex,c("Thailand", 63, -13))
hex = rbind(hex,c("Thailand", 64, -14))
hex = rbind(hex,c("Thailand", 65, -11))
hex = rbind(hex,c("Thailand", 63, -15))

hex = rbind(hex,c("Malaysia", 64, -16))
hex = rbind(hex,c("Malaysia", 65, -17))
hex = rbind(hex,c("Malaysia", 70, -16))
hex = rbind(hex,c("Malaysia", 72, -16))

hex = rbind(hex,c("Singapore", 66, -18))

hex = rbind(hex,c("Cambodia", 65, -13))
hex = rbind(hex,c("Cambodia", 66, -12))

hex = rbind(hex,c("Vietnam", 64, -8))
hex = rbind(hex,c("Vietnam", 66, -8))
hex = rbind(hex,c("Vietnam", 65, -9))
hex = rbind(hex,c("Vietnam", 66, -10))
hex = rbind(hex,c("Vietnam", 67, -11))
hex = rbind(hex,c("Vietnam", 68, -12))
hex = rbind(hex,c("Vietnam", 67, -13))
hex = rbind(hex,c("Vietnam", 68, -8))
hex = rbind(hex,c("Vietnam", 67, -9))
hex = rbind(hex,c("Vietnam", 70, -12))
hex = rbind(hex,c("Vietnam", 69, -13))


hex = rbind(hex,c("Mongolia", 65, 1))

hex = rbind(hex,c("China", 70, 4))
hex = rbind(hex,c("China", 72, 4))
hex = rbind(hex,c("China", 74, 4))
hex = rbind(hex,c("China", 76, 4))
hex = rbind(hex,c("China", 78, 4))
hex = rbind(hex,c("China", 69, 3))
hex = rbind(hex,c("China", 71, 3))
hex = rbind(hex,c("China", 73, 3))
hex = rbind(hex,c("China", 75, 3))
hex = rbind(hex,c("China", 77, 3))

hex = rbind(hex,c("China", 68, 2))
hex = rbind(hex,c("China", 70, 2))
hex = rbind(hex,c("China", 72, 2))
hex = rbind(hex,c("China", 74, 2))
hex = rbind(hex,c("China", 76, 2))
hex = rbind(hex,c("China", 67, 1))
hex = rbind(hex,c("China", 69, 1))
hex = rbind(hex,c("China", 71, 1))
hex = rbind(hex,c("China", 73, 1))
hex = rbind(hex,c("China", 75, 1))

hex = rbind(hex,c("China", 56, 0))
hex = rbind(hex,c("China", 58, 0))
hex = rbind(hex,c("China", 60, 0))
hex = rbind(hex,c("China", 62, 0))
hex = rbind(hex,c("China", 64, 0))
hex = rbind(hex,c("China", 66, 0))
hex = rbind(hex,c("China", 68, 0))
hex = rbind(hex,c("China", 70, 0))
hex = rbind(hex,c("China", 72, 0))
hex = rbind(hex,c("China", 74, 0))

hex = rbind(hex,c("China", 33, -1))
hex = rbind(hex,c("China", 35, -1))
hex = rbind(hex,c("China", 37, -1))
hex = rbind(hex,c("China", 39, -1))
hex = rbind(hex,c("China", 41, -1))
hex = rbind(hex,c("China", 43, -1))
hex = rbind(hex,c("China", 45, -1))
hex = rbind(hex,c("China", 47, -1))
hex = rbind(hex,c("China", 49, -1))
hex = rbind(hex,c("China", 51, -1))

hex = rbind(hex,c("China", 53, -1))
hex = rbind(hex,c("China", 55, -1))
hex = rbind(hex,c("China", 57, -1))
hex = rbind(hex,c("China", 59, -1))
hex = rbind(hex,c("China", 61, -1))
hex = rbind(hex,c("China", 63, -1))
hex = rbind(hex,c("China", 65, -1))
hex = rbind(hex,c("China", 67, -1))
hex = rbind(hex,c("China", 69, -1))
hex = rbind(hex,c("China", 71, -1))

hex = rbind(hex,c("China", 73, -1))
hex = rbind(hex,c("China", 75, -1))
hex = rbind(hex,c("China", 32, -2))
hex = rbind(hex,c("China", 34, -2))
hex = rbind(hex,c("China", 36, -2))
hex = rbind(hex,c("China", 38, -2))
hex = rbind(hex,c("China", 40, -2))
hex = rbind(hex,c("China", 42, -2))
hex = rbind(hex,c("China", 44, -2))
hex = rbind(hex,c("China", 46, -2))

hex = rbind(hex,c("China", 48, -2))
hex = rbind(hex,c("China", 50, -2))
hex = rbind(hex,c("China", 52, -2))
hex = rbind(hex,c("China", 54, -2))
hex = rbind(hex,c("China", 56, -2))
hex = rbind(hex,c("China", 58, -2))
hex = rbind(hex,c("China", 60, -2))
hex = rbind(hex,c("China", 62, -2))
hex = rbind(hex,c("China", 64, -2))
hex = rbind(hex,c("China", 66, -2))

hex = rbind(hex,c("China", 68, -2))
hex = rbind(hex,c("China", 70, -2))
hex = rbind(hex,c("China", 72, -2))
hex = rbind(hex,c("China", 74, -2))
hex = rbind(hex,c("China", 33, -3))
hex = rbind(hex,c("China", 35, -3))
hex = rbind(hex,c("China", 37, -3))
hex = rbind(hex,c("China", 39, -3))
hex = rbind(hex,c("China", 41, -3))
hex = rbind(hex,c("China", 43, -3))

hex = rbind(hex,c("China", 45, -3))
hex = rbind(hex,c("China", 47, -3))
hex = rbind(hex,c("China", 49, -3))
hex = rbind(hex,c("China", 51, -3))
hex = rbind(hex,c("China", 53, -3))
hex = rbind(hex,c("China", 55, -3))
hex = rbind(hex,c("China", 57, -3))
hex = rbind(hex,c("China", 59, -3))
hex = rbind(hex,c("China", 61, -3))
hex = rbind(hex,c("China", 63, -3))

hex = rbind(hex,c("China", 65, -3))
hex = rbind(hex,c("China", 67, -3))
hex = rbind(hex,c("China", 69, -3))
hex = rbind(hex,c("China", 71, -3))
hex = rbind(hex,c("China", 73, -3))
hex = rbind(hex,c("China", 75, -3))
hex = rbind(hex,c("China", 34, -4))
hex = rbind(hex,c("China", 36, -4))
hex = rbind(hex,c("China", 64, -4))
hex = rbind(hex,c("China", 66, -4))

hex = rbind(hex,c("China", 68, -4))
hex = rbind(hex,c("China", 70, -4))
hex = rbind(hex,c("China", 72, -4))
hex = rbind(hex,c("China", 74, -4))
hex = rbind(hex,c("China", 76, -4))
hex = rbind(hex,c("China", 63, -5))
hex = rbind(hex,c("China", 65, -5))
hex = rbind(hex,c("China", 67, -5))
hex = rbind(hex,c("China", 69, -5))
hex = rbind(hex,c("China", 71, -5))

hex = rbind(hex,c("China", 73, -5))
hex = rbind(hex,c("China", 75, -5))
hex = rbind(hex,c("China", 62, -6))
hex = rbind(hex,c("China", 64, -6))
hex = rbind(hex,c("China", 66, -6))
hex = rbind(hex,c("China", 68, -6))
hex = rbind(hex,c("China", 70, -6))
hex = rbind(hex,c("China", 72, -6))
hex = rbind(hex,c("China", 74, -6))
hex = rbind(hex,c("China", 63, -7))

hex = rbind(hex,c("China", 65, -7))
hex = rbind(hex,c("China", 67, -7))
hex = rbind(hex,c("China", 69, -7))
hex = rbind(hex,c("China", 71, -7))
hex = rbind(hex,c("China", 73, -7))

hex = rbind(hex,c("North Korea", 78, 2))
hex = rbind(hex,c("North Korea", 77, 1))
hex = rbind(hex,c("North Korea", 79, 3))

hex = rbind(hex,c("South Korea", 80, 2))
hex = rbind(hex,c("South Korea", 79, 1))
hex = rbind(hex,c("South Korea", 81, 1))
hex = rbind(hex,c("South Korea", 80, 0))
hex = rbind(hex,c("South Korea", 82, 0))
hex = rbind(hex,c("South Korea", 81, -1))

hex = rbind(hex,c("Japan", 86, -2))
hex = rbind(hex,c("Japan", 83, -3))
hex = rbind(hex,c("Japan", 85, -1))
hex = rbind(hex,c("Japan", 87, -1))
hex = rbind(hex,c("Japan", 88, 0))
hex = rbind(hex,c("Japan", 90, 0))
hex = rbind(hex,c("Japan", 91, 1))
hex = rbind(hex,c("Japan", 92, 2))
hex = rbind(hex,c("Japan", 89, 1))
hex = rbind(hex,c("Japan", 90, 2))

hex = rbind(hex,c("Japan", 90, 4))
hex = rbind(hex,c("Japan", 92, 4))
hex = rbind(hex,c("Japan", 89, -1))

hex = rbind(hex,c("Taiwan", 78, -6))
hex = rbind(hex,c("Hong Kong", 75, -7))
hex = rbind(hex,c("Macau", 74, -8))

hex = rbind(hex,c("Philippines", 78, -10))
hex = rbind(hex,c("Philippines", 77, -11))
hex = rbind(hex,c("Philippines", 79, -11))
hex = rbind(hex,c("Philippines", 78, -12))
hex = rbind(hex,c("Philippines", 80, -12))
hex = rbind(hex,c("Philippines", 80, -14))
hex = rbind(hex,c("Philippines", 79, -15))
hex = rbind(hex,c("Philippines", 79, -13))
hex = rbind(hex,c("Philippines", 78, -14))
hex = rbind(hex,c("Philippines", 81, -13))

hex = rbind(hex,c("Indonesia", 71, -17))
hex = rbind(hex,c("Indonesia", 69, -17))
hex = rbind(hex,c("Indonesia", 72, -18))
hex = rbind(hex,c("Indonesia", 73, -17))
hex = rbind(hex,c("Indonesia", 70, -18))
hex = rbind(hex,c("Indonesia", 62, -18))
hex = rbind(hex,c("Indonesia", 63, -19))
hex = rbind(hex,c("Indonesia", 64, -20))
hex = rbind(hex,c("Indonesia", 66, -20))
hex = rbind(hex,c("Indonesia", 67, -21))

hex = rbind(hex,c("Indonesia", 69, -21))
hex = rbind(hex,c("Indonesia", 71, -21))
hex = rbind(hex,c("Indonesia", 73, -21))
hex = rbind(hex,c("Indonesia", 75, -21))
hex = rbind(hex,c("Indonesia", 75, -19))
hex = rbind(hex,c("Indonesia", 76, -18))
hex = rbind(hex,c("Indonesia", 77, -19))
hex = rbind(hex,c("Indonesia", 87, -19))
hex = rbind(hex,c("Indonesia", 89, -19))
hex = rbind(hex,c("Indonesia", 88, -20))

hex = rbind(hex,c("Indonesia", 90, -20))
hex = rbind(hex,c("Indonesia", 79, -21))
hex = rbind(hex,c("Indonesia", 81, -21))
hex = rbind(hex,c("Indonesia", 86, -18))
hex = rbind(hex,c("Indonesia", 80, -18))
hex = rbind(hex,c("Indonesia", 83, -19))
hex = rbind(hex,c("Indonesia", 74, -16))

hex = rbind(hex,c("Timor-Leste", 81, -21))
hex = rbind(hex,c("Brunei", 71, -15))
hex = rbind(hex,c("Papua New Guinea", 91, -19))
hex = rbind(hex,c("Solomon Islands", 93, -19))

hex = rbind(hex,c("Vanuatu", 95, -21))
hex = rbind(hex,c("New Caledonia", 96, -22))
hex = rbind(hex,c("Fiji", 97, -21))
hex = rbind(hex,c("Wallis and Futuna", 98, -20))
hex = rbind(hex,c("Samoa", 100, -20))
hex = rbind(hex,c("American Samoa", 102, -20))
hex = rbind(hex,c("Tokelau", 99, -19))
hex = rbind(hex,c("Tuvalu", 97, -19))
hex = rbind(hex,c("Niue", 101, -21))
hex = rbind(hex,c("Cook Islands", 102, -22))
hex = rbind(hex,c("French Polynesia", 105, -21))
hex = rbind(hex,c("Tonga", 98, -22))
hex = rbind(hex,c("Nauru", 95, -17))
hex = rbind(hex,c("Marshall Islands", 97, -15))
hex = rbind(hex,c("Federated States of Micronesia", 93, -15))
hex = rbind(hex,c("Palau", 85, -15))
hex = rbind(hex,c("Guam", 89, -13))
hex = rbind(hex,c("Northern Mariana Islands", 90, -12))
hex = rbind(hex,c("Kiribati", 103, -17))
hex = rbind(hex,c("Australia", 86, -24))
hex = rbind(hex,c("Australia", 88, -24))
hex = rbind(hex,c("Australia", 90, -24))

hex = rbind(hex,c("New Zealand", 97, -25))


#######################################################################
#######################################################################
## South America
#######################################################################
#######################################################################
hex = rbind(hex,c("Brazil", -21, -15))
hex = rbind(hex,c("Brazil", -22, -14))
hex = rbind(hex,c("Brazil", -23, -13))
hex = rbind(hex,c("Brazil", -22, -16))
hex = rbind(hex,c("Brazil", -23, -17))
hex = rbind(hex,c("Brazil", -24, -16))
hex = rbind(hex,c("Brazil", -23, -15))
hex = rbind(hex,c("Brazil", -24, -14))
hex = rbind(hex,c("Brazil", -25, -13))
hex = rbind(hex,c("Brazil", -27, -13))

hex = rbind(hex,c("Brazil", -28, -14))
hex = rbind(hex,c("Brazil", -26, -14))
hex = rbind(hex,c("Brazil", -25, -15))
hex = rbind(hex,c("Brazil", -27, -15))
hex = rbind(hex,c("Brazil", -26, -12))
hex = rbind(hex,c("Brazil", -24, -12))
hex = rbind(hex,c("Brazil", -28, -12))
hex = rbind(hex,c("Brazil", -29, -13))
hex = rbind(hex,c("Brazil", -24, -18))
hex = rbind(hex,c("Brazil", -30, -14))

hex = rbind(hex,c("Brazil", -25, -17))

hex = rbind(hex,c("Uruguay", -25, -19))
hex = rbind(hex,c("Paraguay", -26, -18))
hex = rbind(hex,c("Bolivia", -26, -16))
hex = rbind(hex,c("Bolivia", -27, -17))
hex = rbind(hex,c("Chile", -28, -18))
hex = rbind(hex,c("Chile", -29, -19))

hex = rbind(hex,c("Argentina", -27, -19))
hex = rbind(hex,c("Argentina", -26, -20))
hex = rbind(hex,c("Argentina", -28, -20))
hex = rbind(hex,c("Argentina", -27, -21))
hex = rbind(hex,c("Argentina", -26, -22))

hex = rbind(hex,c("Peru", -28, -16))
hex = rbind(hex,c("Peru", -31, -15))
hex = rbind(hex,c("Peru", -29, -15))
hex = rbind(hex,c("Peru", -32, -14))

hex = rbind(hex,c("Ecuador", -31, -13))
hex = rbind(hex,c("Ecuador", -33, -13))

hex = rbind(hex,c("Colombia", -30, -12))
hex = rbind(hex,c("Colombia", -32, -12))
hex = rbind(hex,c("Colombia", -31, -11))
hex = rbind(hex,c("Colombia", -33, -11))
hex = rbind(hex,c("Colombia", -32, -10))

hex = rbind(hex,c("Venezuela", -29, -11))
hex = rbind(hex,c("Venezuela", -30, -10))
hex = rbind(hex,c("Venezuela", -27, -11))
hex = rbind(hex,c("Venezuela", -28, -10))

hex = rbind(hex,c("Guyana", -26, -10))
hex = rbind(hex,c("Suriname", -25, -11))
hex = rbind(hex,c("French Guiana", -23, -11))

hex = rbind(hex,c("Falkland Islands", -23, -21))
hex = rbind(hex,c("South Georgia and the South Sandwich Islands", -18, -22))


#######################################################################
#######################################################################
## Caribean
#######################################################################
#######################################################################
hex = rbind(hex,c("Aruba", -31, -9))
hex = rbind(hex,c("Curacao", -29, -9))
hex = rbind(hex,c("Caribbean Netherlands", -27, -9))
hex = rbind(hex,c("Trinidad and Tobago", -25, -9))
hex = rbind(hex,c("Grenada", -26, -8))
hex = rbind(hex,c("Barbados", -24, -8))
hex = rbind(hex,c("Saint Vincent and the Grenadines", -25, -7))
hex = rbind(hex,c("Saint Lucia", -23, -7))
hex = rbind(hex,c("Cayman Islands", -34, -4))
hex = rbind(hex,c("Jamaica", -32, -4))
hex = rbind(hex,c("Haiti", -31, -3))
hex = rbind(hex,c("Dominican Republic", -29, -3))
hex = rbind(hex,c("Turks and Caicos Islands", -30, -2))
hex = rbind(hex,c("Bahamas", -31, -1))
hex = rbind(hex,c("Cuba", -34, -2))
hex = rbind(hex,c("Cuba", -32, -2))

hex = rbind(hex,c("Puerto Rico", -28, -4))
hex = rbind(hex,c("British Virgin Islands", -27, -3))
hex = rbind(hex,c("United States Virgin Islands", -26, -4))
hex = rbind(hex,c("Anguilla", -26, -2))
hex = rbind(hex,c("Sint Maarten", -25, -3))
hex = rbind(hex,c("Saint Kitts and Nevis", -27, -5))
hex = rbind(hex,c("Antigua and Barbuda", -24, -4))
hex = rbind(hex,c("Montserrat", -25, -5))
hex = rbind(hex,c("Guadeloupe", -23, -5))
hex = rbind(hex,c("Dominica", -26, -6))
hex = rbind(hex,c("Martinique", -24, -6))


#######################################################################
#######################################################################
## Central America
#######################################################################
#######################################################################
hex = rbind(hex,c("Panama", -33, -9))
hex = rbind(hex,c("Costa Rica", -34, -8))
hex = rbind(hex,c("Nicaragua", -35, -7))
hex = rbind(hex,c("Honduras", -36, -6))
hex = rbind(hex,c("El Salvador", -38, -6))
hex = rbind(hex,c("Guatemala", -39, -5))
hex = rbind(hex,c("Guatemala", -38, -4))
hex = rbind(hex,c("Belize", -37, -5))

hex = rbind(hex,c("Mexico", -40, -4))
hex = rbind(hex,c("Mexico", -39, -3))
hex = rbind(hex,c("Mexico", -37, -3))
hex = rbind(hex,c("Mexico", -41, -3))
hex = rbind(hex,c("Mexico", -43, -3))
hex = rbind(hex,c("Mexico", -44, -2))
hex = rbind(hex,c("Mexico", -42, -2))
hex = rbind(hex,c("Mexico", -43, -1))
hex = rbind(hex,c("Mexico", -45, -1))
hex = rbind(hex,c("Mexico", -42, 0))

hex = rbind(hex,c("Mexico", -44, 0))
hex = rbind(hex,c("Mexico", -46, 0))
hex = rbind(hex,c("Mexico", -47, 1))


#######################################################################
#######################################################################
## North America
#######################################################################
#######################################################################
hex = rbind(hex,c("United States", -45, 1))
hex = rbind(hex,c("United States", -43, 1))
hex = rbind(hex,c("United States", -41, 1))
hex = rbind(hex,c("United States", -39, 1))
hex = rbind(hex,c("United States", -37, 1))
hex = rbind(hex,c("United States", -35, 1))
hex = rbind(hex,c("United States", -33, 1))
hex = rbind(hex,c("United States", -46, 2))
hex = rbind(hex,c("United States", -44, 2))

hex = rbind(hex,c("United States", -42, 2))
hex = rbind(hex,c("United States", -40, 2))
hex = rbind(hex,c("United States", -38, 2))
hex = rbind(hex,c("United States", -36, 2))
hex = rbind(hex,c("United States", -34, 2))
hex = rbind(hex,c("United States", -32, 2))
hex = rbind(hex,c("United States", -31, 3))
hex = rbind(hex,c("United States", -47, 3))
hex = rbind(hex,c("United States", -45, 3))
hex = rbind(hex,c("United States", -43, 3))
hex = rbind(hex,c("United States", -41, 3))
hex = rbind(hex,c("United States", -39, 3))

hex = rbind(hex,c("United States", -37, 3))
hex = rbind(hex,c("United States", -35, 3))
hex = rbind(hex,c("United States", -33, 3))
hex = rbind(hex,c("United States", -48, 4))
hex = rbind(hex,c("United States", -46, 4))
hex = rbind(hex,c("United States", -44, 4))
hex = rbind(hex,c("United States", -42, 4))
hex = rbind(hex,c("United States", -40, 4))
hex = rbind(hex,c("United States", -38, 4))
hex = rbind(hex,c("United States", -36, 4))

hex = rbind(hex,c("United States", -34, 4))
hex = rbind(hex,c("United States", -32, 4))
hex = rbind(hex,c("United States", -30, 4))


hex = rbind(hex,c("Canada", -41, 5))
hex = rbind(hex,c("Canada", -39, 5))
hex = rbind(hex,c("Canada", -37, 5))
hex = rbind(hex,c("Canada", -35, 5))

hex = rbind(hex,c("Saint Pierre and Miquelon", -29, 5))
hex = rbind(hex,c("Bermuda", -24, 2))
hex = rbind(hex,c("Greenland", -24, 10))

hex = rbind(hex,c("Hawaii (US)", 105, -7))

hex$x = as.numeric(hex$x)

hex$y = as.numeric(hex$y)

hexagon = function(x,y, sideLength = 1, col = 3){
  polygon(x + sideLength * c(0,1,1,0,-1,-1),y + sideLength * c(2,1,-1,-2,-1,1)/sqrt(3), border = NA, col = 3)
}

par(mar=c(0,0,0,0))
plot(1:10,type = "n", xlim = c(-55,110), ylim = c(-60,20), asp=1, xaxs = "i", yaxs = "i", axes = FALSE, xlab ="", ylab ="")
plot(1:10,type = "n", xlim = c(0,55), ylim = c(-60,20), asp=1, xaxs = "i", yaxs = "i", axes = FALSE, xlab ="", ylab ="")

for(i in 1:dim(hex)[1]){
  if(!is.na(hex$x[i]) & !is.na(hex$y[i])){
    hexagon(hex$x[i],sqrt(3)*hex$y[i], 0.9, col = c(2,3)[1+hex$UN[i]])
    text(hex$x[i],sqrt(3)*hex$y[i],label = substr(hex$country[i],1,2))
  }
}
